name: Build Tarball

on:
  push:
    branches:
      - branchAutomake

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install automake autoconf

      - name: Run autogen
        run: autoreconf -i

      - name: Configure
        run: ./configure

      - name: Build and create tarball
        run: make dist
        
