name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up C++ build environment
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Build with Makefile
        run: make
